# Generated by Django 4.2.9 on 2024-01-14 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iElect', '0002_candidate_total_vote_controlvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlvote',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iElect.election'),
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iElect.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
