# Generated by Django 4.2.9 on 2024-01-15 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iElect', '0003_alter_controlvote_position_uservote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlvote',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iElect.candidate'),
        ),
    ]
